apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: "redis-4"
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: redis
        name: "redis-4"
    spec:
      containers:
        - name: redis
          image: "redis:3.2.8"
          command:
            - "redis-server"
          args:
            - "/etc/redis/redis.conf"
            - "--protected-mode"
            - "no"
          resources:
            requests:
              cpu: "100m"
              memory: "100Mi"
          ports:
            - name: redis
              containerPort: 6379
              protocol: "TCP"
            - name: cluster
              containerPort: 16379
              protocol: "TCP"
          volumeMounts:
            - name: "redis-conf"
              mountPath: "/etc/redis"
            - name: "redis-data"
              mountPath: "/var/lib/redis"
      volumes:
        - name: "redis-data"
          gcePersistentDisk:
            pdName: "redis-4"
            fsType: ext4
        - name: "redis-conf"
          configMap:
            name: "redis-conf"
            items:
              - key: "redis.conf"
                path: "redis.conf"
